modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/${github_user}/${github_repo}/issues"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
mandatory=true
versionRange="${ae2_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="${jei_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="crafttweaker"
mandatory=false
versionRange="${crt_version_range}"
ordering="AFTER"
side="BOTH"
