name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '1.16'
    tags:
      - 'v1.16-*.*.*'
  pull_request:
    branches:
      - '1.16'

env:
  JAVA_DIST: 'zulu'
  JAVA_VERSION: 11
  JAR_NAME: 'templatemod'
  FILE_NAME: 'TemplateMod'

jobs:
  build:
    name: Build & Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      #      - name: SonarCloud Cache
      #        uses: actions/cache@v2
      #        with:
      #          path: ~/.sonar/cache
      #          key: ${{ runner.os }}-sonar
      #          restore-keys: ${{ runner.os }}-sonar

      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build --stacktrace --no-daemon
        # ./gradlew build sonarqube --stacktrace --no-daemon

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v1.16-')
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble the jar
        run: |
          chmod +x ./gradlew
          ./gradlew jar --no-daemon

      - name: JAR manipulation
        run: |
          echo "JAR_FILE=$(find build/libs/${{ env.JAR_NAME }}-*-*.jar)" >> $GITHUB_ENV
          echo ${JAR_FILE%.*} | awk -F- '{ print "MINECRAFT_VERSION=" $2; print "MOD_VERSION=" $3; }' >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE_NAME }}-${{ env.MINECRAFT_VERSION }}-${{ env.MOD_VERSION }}.jar
          path: ${{ env.JAR_FILE }}

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.JAR_FILE }}

      - name: Upload to CurseForge
        run: ./gradlew curseforge
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          FILE_NAME: ${{ env.FILE_NAME }}
